# Generated by Django 5.1.4 on 2025-01-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_contactus_remove_car_price_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='suitcase_capacity',
            field=models.IntegerField(default=100.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
